sinks:
  - package: "github.com/hyperledger/fabric/core/chaincode/shim"
    method: "PutState"
    receiver: "shim.ChaincodeStubInterface"
  - package: "cc-checker/ccs/hello"
    method: "sink"
sources:
  - package: "math/rand"
    method: "Int"
    tag: "random"

  - package: "time"
    method: "Now"
    tag: "time"

excludes:
  - package: "github.com/hyperledger/fabric/core/chaincode/shim"
    method: "Error"
